### ISSUE TITLE
Dockerize reviewBot

### ISSUE THREAD

**Issue by eiselems** [eiselems/mattermost-reviewbot#4]
It would really helpful to have a dockerImage which you could just drop somewhere and it works just out of the box.

Keep in mind: The data folder should be backed by a volume (if there are some prerequisites necessary)

**Comment by kmjayadeep** [comment]
Can I work on this? I will add dockerfile and docker-compose.yml file

**Comment by eiselems** [comment]
Of course :) 
Sadly I think the documentation is really minimalistic.
Currently the main file is running once and then exiting.

I did this because it makes the error handling easier.

What do you think does make more sense:
a) to run it in an interval inside the js file - do proper error handling so it does not exit when facing an error
b) just executing the script periodically using cron?

I think we should go for a) since this would make alive/health checking probably easier

**Comment by kmjayadeep** [comment]
option a seems better for me too. We can write a separate start file, maybe bin/start where we can run the function inside a timer.
